auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
# rdiscount extensions: [smart]
rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes   # footnotes
    - smart         # typographic substitutions with SmartyPants
